<?php
/**
 * @file
 * fillpdf_feature.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function fillpdf_feature_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-fillpdf_form-field_credit_line_and_copyright'.
  $field_instances['node-fillpdf_form-field_credit_line_and_copyright'] = array(
    'bundle' => 'fillpdf_form',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '(e.g. CC-BY-­SA; see https://creativecommons.org or http://copyright.gov for more information)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_credit_line_and_copyright',
    'label' => 'credit line and copyright',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-fillpdf_form-field_filename'.
  $field_instances['node-fillpdf_form-field_filename'] = array(
    'bundle' => 'fillpdf_form',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_filename',
    'label' => 'Filename',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-fillpdf_form-field_other_identifying_informat'.
  $field_instances['node-fillpdf_form-field_other_identifying_informat'] = array(
    'bundle' => 'fillpdf_form',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_other_identifying_informat',
    'label' => 'Other Identifying Information',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-fillpdf_form-field_photographer'.
  $field_instances['node-fillpdf_form-field_photographer'] = array(
    'bundle' => 'fillpdf_form',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_photographer',
    'label' => 'Photographer/Author',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('(e.g. CC-BY-­SA; see https://creativecommons.org or http://copyright.gov for more information)');
  t('Filename');
  t('Other Identifying Information');
  t('Photographer/Author');
  t('credit line and copyright');

  return $field_instances;
}
