<?php

/**
 * @file
 *  Provides a generic but powerful API for web services.
 */

 /*
 * Services UI is defined in the export-ui plugin.
 */
function service_rest_login_menu() {
  $items = array();


  return $items;
}

function service_rest_login_user_login(&$edit, $account) {
  foreach($edit as $key => $user_data) {
     if($key == 'complete form') {
      $destination = $user_data['#action'];
       drupal_goto($destination);
     }
  }
}


/**
 * Implements hook_form_alter().
 */
function service_rest_login_form_alter(&$form, $form_state, $form_id) {
// echo "form id ".$form_id;exit;
  switch ($form_id) {
    case 'user_login_block':

    //  $form['#submit'][] = 'after_login_submit';
      array_unshift($form['#validate'], 'insert_before_login_submit');
      //echo "<pre>";  print_r($form); echo "</pre>";exit;

      break;
    case 'user_login' :
       
      //$form['#submit'][] = 'after_login_submit';
      array_unshift($form['#validate'], 'insert_before_login_submit');
      
      //array_unshift($form['#submit'], 'insert_before_login_submit');
      // echo "<pre>";  print_r($form); echo "</pre>";exit;
      break;
  }
}

/*function after_login_submit($form, &$form_state) {
//   echo "<pre> login submit ";  print_r($form_state); echo "</pre>";exit;

  $form_state['complete form']['#action'] = '/about';
  // echo "<pre> in after ";   print_r($form_state); echo "</pre>";exit;
}*/

function insert_before_login_submit($form, &$form_state) {
 //  echo "<pre> formstate ";  print_r($form_state); echo "</pre>";exit;
 // $form['#actions'] = '/user';
  $values = $form_state['values']; 
  $name = $values['name'];
  $pass = $values['pass'];  

  //$base_url = 'http://stage-www-u.lcacommons.gov/rest';
  $base_url = 'http://gmod-dev.nal.usda.gov/webapp/web_login?username='.$name.'&password='.$pass;

  $data = array();
  //$data = drupal_json_encode($data);
  $options = array(
    'headers' => array(
      'Content-Type' => 'application/json',
    ),
    'method' => 'GET',
    'data' => $data
  );

  $response =  drupal_http_request($base_url, $options);

//echo "<bR> Before response ".$response->redirect_url;
//  $response->redirect_url = "https://stage-www.lcacommons.gov/discovery/login/ajaxSuccess";

  $data = json_decode($response->data);
 // echo "<pre> "; print_r($response); print_r($data); echo "</pre>";exit;

  //IF Django authentication is success then check the user exists in drupal or not
  //If not insert into drupal
  //If yes then directly login into the drupal system
  //If java authentication fails then do nothing
  if(($response->code == 200) && !empty($data->user)) {
    // Create a cookie for the browser.
    setcookie('sessionid', $data->sessionid);   
    $is_account_exists =  db_query("select * from {users} where name = :name", array(':name' => $name))->fetchObject();
    if(!$is_account_exists) {
      //If not account then insert user details into drupal users table
      //Register this new user.
      require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
      require_once DRUPAL_ROOT . '/' . variable_get('bootstrap.inc', 'includes/bootstrap.inc');

      $userinfo = array(
        'name' => $name,
        'pass' => $pass,
        'mail' => $data->email,
        'init' => $name,
        'status' => 1,
        'access' => REQUEST_TIME,
        'login' => REQUEST_TIME
      );

      $account = user_save(drupal_anonymous_user(), $userinfo);
      $form_state['uid'] = $account->uid;

      // Terminate if an error occurred during user_save().
      if (!$account) {
        drupal_set_message(t("Error saving user account."), 'error');
        return;
      }
    }
  }
}

